version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    volumes:
      - game_data:/app/data
    env_file:
      - .env
    environment:
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
    depends_on:
      - backend
    restart: always

volumes:
  game_data:
